### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by shtirlic** [eitoball/net-ping#10]
Maybe, we can set `pcmd` to `ping6` somehow in external ping?
or two methods `ping` and `ping6`

**Comment by djberg96** [comment]
@shtirlic Looks like he added a ping6 method already.

**Comment by shtirlic** [comment]
@djberg96 ohhhh yes, I will check this out, will try to refactor the copy/paste
PS Looked into sources in your repo, but forget to check the fork's sources)
