### ISSUE TITLE
External ping command fails on Void Linux (`-i` argument should come before host?)

### ISSUE THREAD

**Issue by rlue** [eitoball/net-ping#14]
I don't exactly know the details; just reporting on behalf of @emacsomancer, who [filed an issue on a project of mine](https://github.com/rlue/little_red_flag/issues/1#issuecomment-301964404), arising from this library's `External#ping` command.

From his post:

I'm on Linux (Void Linux; using libressl instead of openssl, and musl rather than glibc, if that makes a difference).

> If I run:
> 
>     ping -c 1 -W 5 imap.gmail.com -i 1
> 
> the output is:
> 
>     ping: unknown host -i
> 
> (though running `ping -c 1 -W 5 imap.gmail.com`, produces:
> 
>     PING gmail-imap.l.google.com (209.85.200.109) 56(84) bytes of data.
>     64 bytes from jl-in-f109.1e100.net (209.85.200.109): icmp_seq=1 ttl=44 time=120 ms
> 
>     --- gmail-imap.l.google.com ping statistics ---
>     1 packets transmitted, 1 received, 0% packet loss, time 0ms
>     rtt min/avg/max/mdev = 120.149/120.149/120.149/0.000 ms
> 
> )
> 
>     $ echo $?
>     2

**Comment by chernesk** [comment]
I'll look into it. Thanks for the report.

**Comment by spijet** [comment]
Any updates on this issue? It (together with #12) makes this gem's external module unusable on Alpine Linux, because it can use either Busybox `ping` (which doesn't recognize `-i` option) or iputils `ping` (which requires target hostname to be the last argument, so `ping google.com -i 1` won't work).

**Comment by chernesk** [comment]
Sorry for the delay. I'll work on it in a few hours.

- Chris


On Tue, Mar 6, 2018, at 11:38 AM, Serge Tkatchouk wrote:
> Any updates on this issue? It and #12[1] together make this gem's
> external module unusable on Alpine Linux, because it can use either
> Busybox ping (which doesn't recognize -i option) or iputils ping
> (which requires target hostname to be the last argument, so ping
> google.com -i 1 won't work).> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/chernesk/net-ping/issues/12
  2. https://github.com/chernesk/net-ping/issues/14#issuecomment-370844062

**Comment by spijet** [comment]
Thanks a lot! I'm gonna test it today and will let you know if it works.

**Comment by spijet** [comment]
Yes, it works! Both for `iputils` ping, and for `busybox` one. Thank you a lot!!

**Comment by rlue** [comment]
I don't run Alpine or Void Linux, so I'll just take @spijet's word for it.
