### ISSUE TITLE
More relevant duration

### ISSUE THREAD

**Issue by Qwertyn** [eitoball/net-ping#2]
If end_time calculate a little earlier, the duration would be more relevant.

``` ruby
# lib/net/ping/external.rb
...
Open3.popen3(*pcmd) do |stdin, stdout, stderr, thread|
  stdin.close
  @end_time = Time.now # <-------
  err = stderr.gets # Can't chomp yet, might be nil
...
# There is no duration if the ping failed
@duration = @end_time - start_time if bool
...
```

What it can be fraught with?
(What negative consequences can be?)

**Comment by chernesk** [comment]
I'm looking into this. Thank you for the submission.

**Comment by chernesk** [comment]
Sorry that this has taken so long to respond to. I have tried a number of scenarios with your suggestion and they all seem to work correctly. 

Merged.
