### ISSUE TITLE
Largely unmaintained

### ISSUE THREAD

**Issue by chernesk** [eitoball/net-ping#26]
I am finding myself unable, with family and work schedules, to maintain this gem. While I would love to be able to, it's not fair to the community for me to take months sometimes to release fixes.

Please contact me at chris@tinderglow.com or on here if you would like to maintain this gem.

**Comment by eitoball** [comment]
@chernesk I would like to maintain this gem.

**Comment by chernesk** [comment]
@eitoball Sounds good. Sorry I didn't respond before. I was on vacation. I may have missed your email before, but please contact me at chris@tinderglow.com so that we can work out the details.

**Comment by eitoball** [comment]
It has been moved to https://github.com/eitoball/net-ping
