### ISSUE TITLE
Release 1.7.8 having the same External ping duration bug as #2

### ISSUE THREAD

**Issue by otzy007** [eitoball/net-ping#5]
Hi,

It looks like 1.7.8 release on rubygems has this bug with Ping::External where the time is incorrectly computed

```
Open3.popen3(*pcmd) do |stdin, stdout, stderr, thread|
          stdin.close
          @end_time = Time.now
```

It's the same bug found on #2 but fixed on master.
Wasn't this bug fixed on 1.7.8?
Also the changelog is stopped at 1.7.7 https://github.com/chernesk/net-ping/blob/master/CHANGES

**Comment by chernesk** [comment]
Thank you for the bug report. I'll check this out and get a fix out as soon as I can.

**Comment by otzy007** [comment]
ok. Thank you 😀

**Comment by chernesk** [comment]
I believe this was fixed with v2.0.0. Please re-open if this is still an issue.

**Comment by otzy007** [comment]
@chernesk Thank you. I'll check and get back to you.

**Comment by otzy007** [comment]
I can confirm that on v2 the response time is right. Thank you 😀

**Comment by chernesk** [comment]
Thanks @otzy007..
