### ISSUE TITLE
ICMP require root privileges 

### ISSUE THREAD

**Issue by HoneyryderChuck** [eitoball/net-ping#6]
https://github.com/chernesk/net-ping/blob/master/lib/net/ping/icmp.rb#L31

Why? 

Coming from https://github.com/djberg96/net-ping/issues/54#issuecomment-173235123

**Comment by chernesk** [comment]
I will check this out and get back to you as soon as I can. Thanks for the question!

**Comment by djberg96** [comment]
@TiagoCardoso1983 because creating an ICMP packet requires a raw socket, and creating raw sockets requires root privileges.

**Comment by HoneyryderChuck** [comment]
Yup, I've found that out since then, it sucks. how does the `ping` cli tool gets away with it? That would be interesting to know.

**Comment by djberg96** [comment]
@TiagoCardoso1983 Your ping command is setuid root.

**Comment by HoneyryderChuck** [comment]
it is clear now, thx.
