### ISSUE TITLE
`The specification for net-ping-2.0.0 is corrupt`

### ISSUE THREAD

**Issue by ShockwaveNN** [eitoball/net-ping#8]
Hi, if i try to install 
`gem install net-ping`
and got an error:

```
ERROR:  Error installing net-ping:                                                                                                                                                      
        The specification for net-ping-2.0.0 is corrupt (SyntaxError) 
```

**Comment by chernesk** [comment]
Thanks. I'll look at it and try to install it fresh.. Sorry about that.
-Chris

On Fri, Aug 5, 2016, at 10:05 AM, Pavel Lobashov wrote:

> Hi, if i try to install
> gem install net-ping
>  and got an error:
> 
> ERROR:  Error installing net-ping: The specification for net-ping-
> 2.0.0 is corrupt (SyntaxError)
> 
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:
1. https://github.com/chernesk/net-ping/issues/8

**Comment by chernesk** [comment]
I removed the gem from rubygems and will look at it later today..

On Fri, Aug 5, 2016, at 10:05 AM, Pavel Lobashov wrote:

> Hi, if i try to install
> gem install net-ping
>  and got an error:
> 
> ERROR:  Error installing net-ping: The specification for net-ping-
> 2.0.0 is corrupt (SyntaxError)
> 
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:
1. https://github.com/chernesk/net-ping/issues/8

**Comment by ShockwaveNN** [comment]
I found a problem in your gemspec, fixed it. 
Tested it and it should work fine.

```
gem install net-ping-2.0.0.gem 
Successfully installed net-ping-2.0.0
Parsing documentation for net-ping-2.0.0
Installing ri documentation for net-ping-2.0.0
Done installing documentation for net-ping after 0 seconds
1 gem installed
```

**Comment by chernesk** [comment]
Appreciate that. Will push it up in an hour or so.

On Fri, Aug 5, 2016, at 10:07 AM, Pavel Lobashov wrote:

> I found a problem in your gemspec, fixed it.
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:
1. https://github.com/chernesk/net-ping/issues/8#issuecomment-237859842
